# Generated by Django 4.2.6 on 2023-10-18 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("protagonist", models.CharField(max_length=50)),
                ("poster", models.ImageField(upload_to="")),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("coming-up", "Coming Up"),
                            ("starting", "Starting"),
                            ("running", "Running"),
                            ("finished", "Finished"),
                        ],
                        default="coming-up",
                        max_length=20,
                    ),
                ),
                ("ranking", models.IntegerField(db_index=True, default=0)),
            ],
        ),
    ]
